"""Repository interfaces — domain layer contracts (Application Layer §1:
one repository per aggregate root, coarse-grained ``get``/``save`` only).
Concrete SQLAlchemy implementations live in
``contexts/identity/infrastructure/repositories.py``; application services
and command handlers depend on these interfaces, never the concrete class
(dependency inversion, Architecture Redesign §9).
"""

from __future__ import annotations

from typing import Protocol

from georisk.contexts.identity.domain.entities import Role, Tenant, User
from georisk.contexts.identity.domain.tokens import (
    InvitationToken,
    PasswordResetToken,
    RefreshToken,
)
from georisk.contexts.identity.domain.value_objects import (
    RefreshTokenId,
    RoleId,
    RoleName,
    TenantId,
    UserId,
)


class TenantRepository(Protocol):
    async def get_by_id(self, tenant_id: TenantId) -> Tenant | None: ...
    async def get_by_slug(self, slug: str) -> Tenant | None: ...
    async def slug_exists(self, slug: str) -> bool: ...
    async def save(self, tenant: Tenant) -> None: ...


class RoleRepository(Protocol):
    async def get_by_id(self, role_id: RoleId) -> Role | None: ...
    async def get_by_name(self, name: RoleName) -> Role | None: ...
    async def list_all(self) -> list[Role]: ...


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UserId) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def email_exists(self, email: str) -> bool: ...
    async def list_by_tenant(
        self, tenant_id: TenantId, *, limit: int, cursor: str | None
    ) -> tuple[list[User], str | None, bool]: ...
    async def count_active_owners(self, tenant_id: TenantId) -> int: ...
    async def save(self, user: User, *, expected_version: int | None = None) -> None: ...


class RefreshTokenRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def save(self, token: RefreshToken) -> None: ...
    async def revoke_all_active_for_user(
        self, user_id: UserId, *, reason: str
    ) -> list[RefreshTokenId]: ...


class PasswordResetTokenRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def save(self, token: PasswordResetToken) -> None: ...


class InvitationTokenRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> InvitationToken | None: ...
    async def get_active_for_user(self, user_id: UserId) -> InvitationToken | None: ...
    async def save(self, token: InvitationToken) -> None: ...
