"""Independent minimal aggregates (Domain Model §1's pattern, applied to
RefreshToken/PasswordResetToken/InvitationToken exactly as it was applied to
SensorReading — high-volume-ish, append-mostly records referencing a parent
by ID rather than nested inside it, so issuing/rotating a token never
contends with the User aggregate's own lock).

All three store only a hash of the opaque token value — the raw token is
generated by the application layer (application/services.py), handed to
the client once, and never persisted in recoverable form.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

from georisk.contexts.identity.domain.errors import InvalidOrExpiredTokenError
from georisk.contexts.identity.domain.value_objects import (
    InvitationTokenId,
    PasswordResetTokenId,
    RefreshTokenId,
    TenantId,
    UserId,
)

REFRESH_TOKEN_TTL = timedelta(days=30)
PASSWORD_RESET_TOKEN_TTL = timedelta(hours=1)
INVITATION_TOKEN_TTL = timedelta(days=7)


@dataclass(slots=True)
class RefreshToken:
    id: RefreshTokenId
    user_id: UserId
    tenant_id: TenantId
    token_hash: str
    issued_at: datetime
    expires_at: datetime
    revoked_at: datetime | None = None
    replaced_by_id: RefreshTokenId | None = None

    @classmethod
    def issue(cls, *, user_id: UserId, tenant_id: TenantId, token_hash: str) -> RefreshToken:
        now = datetime.now(UTC)
        return cls(
            id=RefreshTokenId.new(),
            user_id=user_id,
            tenant_id=tenant_id,
            token_hash=token_hash,
            issued_at=now,
            expires_at=now + REFRESH_TOKEN_TTL,
        )

    def is_active(self, *, now: datetime | None = None) -> bool:
        now = now or datetime.now(UTC)
        return self.revoked_at is None and self.expires_at > now

    def revoke(self, *, replaced_by_id: RefreshTokenId | None = None) -> None:
        self.revoked_at = datetime.now(UTC)
        self.replaced_by_id = replaced_by_id

    def assert_active(self) -> None:
        if not self.is_active():
            raise InvalidOrExpiredTokenError(f"Refresh token {self.id} is expired or revoked")


@dataclass(slots=True)
class PasswordResetToken:
    id: PasswordResetTokenId
    user_id: UserId
    tenant_id: TenantId
    token_hash: str
    created_at: datetime
    expires_at: datetime
    used_at: datetime | None = None

    @classmethod
    def issue(cls, *, user_id: UserId, tenant_id: TenantId, token_hash: str) -> PasswordResetToken:
        now = datetime.now(UTC)
        return cls(
            id=PasswordResetTokenId.new(),
            user_id=user_id,
            tenant_id=tenant_id,
            token_hash=token_hash,
            created_at=now,
            expires_at=now + PASSWORD_RESET_TOKEN_TTL,
        )

    def is_valid(self, *, now: datetime | None = None) -> bool:
        now = now or datetime.now(UTC)
        return self.used_at is None and self.expires_at > now

    def mark_used(self) -> None:
        self.used_at = datetime.now(UTC)

    def assert_valid(self) -> None:
        if not self.is_valid():
            raise InvalidOrExpiredTokenError(
                f"Password reset token {self.id} is expired or already used"
            )


@dataclass(slots=True)
class RevokedAccessToken:
    """A single-session logout denylist entry (Sprint D), keyed by the
    JWT's own ``jti`` — deliberately NOT the same mechanism as ``User.
    token_generation``'s bulk revocation (password reset/suspend/
    deactivate/"revoke all sessions"), since logout must end only the
    caller's current session, never every session for that user.

    ``expires_at`` mirrors the original access token's own expiry (not a
    TTL on this row) purely as bookkeeping for a future pruning job — this
    row is authoritative for revocation regardless of whether that
    timestamp has passed; nothing prunes it automatically yet.
    """

    jti: str
    user_id: UserId
    tenant_id: TenantId
    revoked_at: datetime
    expires_at: datetime

    @classmethod
    def issue(
        cls, *, jti: str, user_id: UserId, tenant_id: TenantId, expires_at: datetime
    ) -> RevokedAccessToken:
        return cls(
            jti=jti,
            user_id=user_id,
            tenant_id=tenant_id,
            revoked_at=datetime.now(UTC),
            expires_at=expires_at,
        )


@dataclass(slots=True)
class InvitationToken:
    id: InvitationTokenId
    user_id: UserId
    tenant_id: TenantId
    token_hash: str
    created_at: datetime
    expires_at: datetime
    used_at: datetime | None = None

    @classmethod
    def issue(cls, *, user_id: UserId, tenant_id: TenantId, token_hash: str) -> InvitationToken:
        now = datetime.now(UTC)
        return cls(
            id=InvitationTokenId.new(),
            user_id=user_id,
            tenant_id=tenant_id,
            token_hash=token_hash,
            created_at=now,
            expires_at=now + INVITATION_TOKEN_TTL,
        )

    def is_valid(self, *, now: datetime | None = None) -> bool:
        now = now or datetime.now(UTC)
        return self.used_at is None and self.expires_at > now

    def mark_used(self) -> None:
        self.used_at = datetime.now(UTC)

    def assert_valid(self) -> None:
        if not self.is_valid():
            raise InvalidOrExpiredTokenError(
                f"Invitation token {self.id} is expired or already used"
            )
